function [data] = dataprep(A)
% La función DATAPREP prepara la estructura que contiene los datos para ser
% procesados y analizados.
% La salida de la función es una estructura de datos llamada DATA, que
% contiene 6 campos: ad, cnad, dcl, cndcl, por y npor correspondientes a
% las matrices de datos de cada uno de los grupo de estudio, considerando
% las siguientes etiquetas:
% ad: Grupo de pacientes con enfermedad de Alzheimer
% cnad: Grupo control de los sujetos con enfermedad de Alzheimer.
% dcl: Grupo de sujetos con deterioro cognitivo leve.
% cndcl: Grupo control de los sujetos con deterioro cognitivo leve.
% por: Grupo de sujetos sanos portadores del gen.
% npor: Grupo de sujetos sanos portadores del gen.
% En cada matriz de tamaño nxm, m representa las variables analizadas y n
% representa las observaciones para cada muestra. Las variables analizadas
% son:
% [:,1] = Difusividad media
% [:,2] = Anisotropía fraccional
% [:,3] = Difusividad axial
% [:,4] = Difusividad radial
% [:,5] = Score del MMSE
% [:,6] = Edad del sujeto
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Matriz de datos para el grupo con enfermedad de Alzheimer;
data.ad(:,:) = [A.DM(categorical(A.Grupo) == 'AD_ADNI') ...
    A.FA(categorical(A.Grupo) == 'AD_ADNI') ...
    A.AD(categorical(A.Grupo) == 'AD_ADNI') ...
    A.RD(categorical(A.Grupo) == 'AD_ADNI') ...
    A.MMSE(categorical(A.Grupo) == 'AD_ADNI') ...
    A.Edad(categorical(A.Grupo) == 'AD_ADNI')...
    A.Sexo(categorical(A.Grupo) == 'AD_ADNI')];
% Matriz de datos para el grupo control de los sujetos con enfermedad de Alzheimer.
data.cnad(:,:) = [A.DM(categorical(A.Grupo) == 'CNAD_ADNI') ...
    A.FA(categorical(A.Grupo) == 'CNAD_ADNI') ...
    A.AD(categorical(A.Grupo) == 'CNAD_ADNI') ...
    A.RD(categorical(A.Grupo) == 'CNAD_ADNI') ...
    A.MMSE(categorical(A.Grupo) == 'CNAD_ADNI') ...
    A.Edad(categorical(A.Grupo) == 'CNAD_ADNI')...
    A.Sexo(categorical(A.Grupo) == 'CNAD_ADNI')];
% Matriz de datos para el grupo de sujetos con deterioro cognitivo leve.
data.dcl(:,:) = [A.DM(categorical(A.Grupo) == 'DCL') ...
    A.FA(categorical(A.Grupo) == 'DCL') ...
    A.AD(categorical(A.Grupo) == 'DCL') ...
    A.RD(categorical(A.Grupo) == 'DCL') ...
    A.MMSE(categorical(A.Grupo) == 'DCL') ...
    A.Edad(categorical(A.Grupo) == 'DCL')...
    A.Sexo(categorical(A.Grupo) == 'DCL')];
% Matriz de datos para el grupo control de los sujetos con deterioro cognitivo leve.
data.cndcl(:,:) = [A.DM(categorical(A.Grupo) == 'CNDCL')...
    A.FA(categorical(A.Grupo) == 'CNDCL')...
    A.AD(categorical(A.Grupo) == 'CNDCL')...
    A.RD(categorical(A.Grupo) == 'CNDCL')...
    A.MMSE(categorical(A.Grupo) == 'CNDCL')...
    A.Edad(categorical(A.Grupo) == 'CNDCL')...
    A.Sexo(categorical(A.Grupo) == 'CNDCL')];
% Matriz de datos para el grupo de sujetos sanos portadores del gen.
data.por(:,:) = [A.DM(categorical(A.Grupo) == 'PORTADORES')...
    A.FA(categorical(A.Grupo) == 'PORTADORES')...
    A.AD(categorical(A.Grupo) == 'PORTADORES')...
    A.RD(categorical(A.Grupo) == 'PORTADORES')...
    A.MMSE(categorical(A.Grupo) == 'PORTADORES')...
    A.Edad(categorical(A.Grupo) == 'PORTADORES')...
    A.Sexo(categorical(A.Grupo) == 'PORTADORES')];
% Matriz de datos para el grupo de sujetos sanos no portadores del gen.
data.npor(:,:) = [A.DM((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48) ...
    A.FA((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48) ...
    A.AD((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48) ...
    A.RD((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48) ...
    A.MMSE((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48) ...
    A.Edad((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48)...
    A.Sexo((categorical(A.Grupo) == 'NO_PORTADORES') & A.Edad <= 48)];
end

